---
version: '3'
volumes:
  redis-data:
services:
  redis-standalone:
    image: docker.io/bitnami/redis:6.2
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
